### ISSUE TITLE
Undefined method `cattr_accessor' 

### ISSUE THREAD

**Issue by waghanza** [carr/phone#52]
Hi,

I use ```phone``` **gem** on a ruby command line app. 

When I run my app, I have directly (just after the ```require 'phone') the folowwing stack trache

~~~ruby
/usr/local/share/gems/gems/phone-1.2.3/lib/country.rb:3:in `<class:Country>': undefined method `cattr_accessor' for Phoner::Country:Class (NoMethodError)
        from /usr/local/share/gems/gems/phone-1.2.3/lib/country.rb:2:in `<module:Phoner>'
        from /usr/local/share/gems/gems/phone-1.2.3/lib/country.rb:1:in `<top (required)>'
        from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/phone-1.2.3/lib/phone.rb:13:in `<top (required)>'
        from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:135:in `require'
        from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:144:in `require'
        from ./sms_sync.rb:9:in `<main>'
~~~

I think this issue is due to **cattr_accessor**, that is ROR only.

Regards,

PS : Just to clarify, the methode I'm trying to use is working on ```irb```

**Comment by elskwid** [comment]
I'm going to close this. Please feel free to reopen or create a new issue if needed. Thanks.

**Comment by Maddin2Code** [comment]
Hello @elskwid,

I was facing this error with v1.2.3 and just want to confirm that it is gone in v1.3.0.beta0. 

Thanks mate!
